data_dir = "node2_data"
rpc_address = "127.0.0.1:50052"

[core.consensus]
# 节点2密钥
pub_key = "030000000000000000000000000000000000000000000000000000000000000001"
prv_key = "0000000000000000000000000000000000000000000000000000000000000002"

[network]
listen_address = "/ip4/127.0.0.1/tcp/8002"
bootstrap_peers = ["/ip4/127.0.0.1/tcp/8001"]
mdns = true