data_dir = "node3_data"
rpc_address = "127.0.0.1:49993"
[core.consensus]
pub_key = "loaded_from_file"
prv_key = "loaded_from_file"
[network]
listen_address = "/ip4/0.0.0.0/tcp/39993"
bootstrap_peers = ["/ip4/127.0.0.1/tcp/39991"]
mdns = false
