data_dir = "node1_data"
rpc_address = "127.0.0.1:50051"

[core.consensus]
# 节点1密钥
pub_key = "020000000000000000000000000000000000000000000000000000000000000001"
prv_key = "0000000000000000000000000000000000000000000000000000000000000001"

[network]
listen_address = "/ip4/127.0.0.1/tcp/8001"
bootstrap_peers = []
mdns = true