data_dir = "/data/node1_data"
rpc_address = "0.0.0.0:50051"

[core]
    [core.consensus]
    pub_key = "020000000000000000000000000000000000000000000000000000000000000001"
    prv_key = "0000000000000000000000000000000000000000000000000000000000000001"

[network]
listen_address = "/ip4/0.0.0.0/tcp/4001"
bootstrap_peers = []
mdns = true
