[package]
name = "db_test"
version = "0.1.0"
edition = "2021"

[dependencies]
norn-storage = { workspace = true }
norn-common = { workspace = true }
tokio = { workspace = true }
tempfile = "3.8"
chrono = { workspace = true }