[package]
name = "norn-network"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { workspace = true }
libp2p = { workspace = true }
tracing = { workspace = true }
anyhow = { workspace = true }
norn-common = { workspace = true }
serde = { workspace = true }
